### PR TITLE
[91] Enable provisioning for the examples instead of relying on a server built in the test suite.

### LINKED ISSUE #91: Migrate the example standalone XML files to use either YAML configuration files or CLI to provision a server
Currently in the examples a `standalone.xml.*` file is copied from the `ssl` directory. We should use either CLI to configure a server or use YAML to overlay the configure. This allows the configuration to be up to date with the version of WildFly we're using instead of a static version set to a specific WildFly release.

### PR DESCRIPTION
**Pull request by jamezp**
Remove the standalone.xml.* pre-configured files in favor of using CLI to configure servers.

We could consider moving to YAML configurations instead of CLI in once we move to WildFly 28. For now, I think it's cleaner to use CLI.

Creating as a draft for now because it relies on #90 

resolves #91

### CODE REVIEW

**Comment by ronsigal** [comment]
This is great. Thanks, @jamezp!!. I'll adapt the same for my GrpcToJakartaRESTTest.

**Review by ronsigal — APPROVED** [review]

**Comment by ronsigal** [comment]
@jamezp, is this ready to merge?

**Comment by jamezp** [comment]
@ronsigal I think so as long as everyone else is good with it. I didn't have much luck with YAML.

**Comment by ronsigal** [comment]
I created pull request https://github.com/wildfly-extras/wildfly-grpc-feature-pack/pull/103 to bump the wildfly plugin.

**Comment by ronsigal** [comment]
I'm not sure if this is a real problem, but, when I re-run an example, I get
```
{
    "outcome" => "failed",
    "failure-description" => "WFLYCTL0212: Duplicate resource [
    (\"subsystem\" => \"elytron\"),
    (\"key-store\" => \"key-store-afcdd1f8-d1a7-4137-aa13-c45237e32428\")
]",
    "rolled-back" => true
}
```
Is there a way to remove the keystores when the server shuts down?

**Comment by jamezp** [comment]
No, but there is a way to not add them if they already exist which is probably the way to go. I'll have a look at that probably tomorrow. I'm working on a WildFly issue ATM.

**Comment by ronsigal** [comment]
Cool. Thanks!!

**Review by hpehl — APPROVED** [review]
I don't have much time for a review, but I trust this is all good. So LGTM!

**Pull request merged**
