### PR TITLE
Allow multiple deployments share a single port

### PR DESCRIPTION
**Pull request by ronsigal**
This pull request supercedes https://github.com/wildfly-extras/wildfly-grpc-feature-pack/pull/45

The main change: before, each deployment was handled by a new GrpcServerService, which tries to open its own port. Now, one GrpcServerService is created when the first gRPC deployment is detected. For subsequent gRPC deployments, the server classes are added to the GrpcServerService. When GrpcServerService is started, all server classes are registered.

It is now possible to deploy both wildfly-grpc-examples-helloworld-service-0.0.4-SNAPSHOT.jar  and wildfly-grpc-examples-chat-service-0.0.4-SNAPSHOT.jar and use both clients.

Another change is the addition of GreeterClientSSL and ChatClientSSL. The example projects are not yet configured to run the SSL versions out of the box.

### CODE REVIEW

**Review by hpehl — APPROVED** [review]
LGTM! Fixing the fixed port issue is a big step forward. Also good to see improvements in the SSL setup. Well done!

Thanks @ronsigal

**Comment by ronsigal** [comment]
Thanks, @hpehl. Next, I'll go back to working on the properties.

**Comment by ronsigal** [comment]
This pull request is superseded by https://github.com/wildfly-extras/wildfly-grpc-feature-pack/pull/51. I'll leave this one open for now, for historical reference, until we merge something.

**Comment by hpehl** [comment]
Close this one after #51 has been merged.

**Pull request closed without merging**
