### PR TITLE
Simplified treatment of attributes as per pull request 41

### PR DESCRIPTION
**Pull request by ronsigal**
Responds to suggestions in https://github.com/wildfly-extras/wildfly-grpc-feature-pack/pull/41 and includes fixes from https://github.com/wildfly-extras/wildfly-grpc-feature-pack/pull/50

### CODE REVIEW

**Comment by ronsigal** [comment]
The most recent commit adds configuration properties from NettyServerBuilder and its ancestors. Also, made some changes to the process of starting and restarting GrpcServerService. In particular, added "serverRestarting" flag.

**Comment by ronsigal** [comment]
Should also make SHUTDOWN_TIMEOUT configurable.

**Comment by ronsigal** [comment]
Superceded by https://github.com/wildfly-extras/wildfly-grpc-feature-pack/pull/53

**Comment by ronsigal** [comment]
I've been working on verifying that one-way and two-way SSL/TLS connections work. Mostly I've been running the helloworld example manually. I've added a command line parameter to GreeterClient which takes values "none", "oneway", and "twoway" and accesses the appropriate certificate files in src/main/resources. Also, I've added a bash script configure which copies a standalone.xml file and the appropriate certificate files to build/target/wildfly-27.0.0.Final-grpc-0.0.4-SNAPSHOT/standalone/configuration and also copies examples/$EXAMPLE/service/target/wildfly-grpc-examples-$EXAMPLE-service-0.0.4-SNAPSHOT.jar to build/target/wildfly-27.0.0.Final-grpc-0.0.4-SNAPSHOT/standalone/deployments. If I'm not mistaken, this can be done programmatically using the management interface, but I don't want to spend the time right now to figure it out.

**Comment by jamezp** [comment]
IMO it's best to use CLI. It's really difficult to keep configuration files in sync with what is happening upstream.

**Comment by ronsigal** [comment]
Hey @jamezp, I'm sure you're right. I just didn't want to take the time to figure it out right now, but I will. I want to spend some time on the gRPC bridge project.

**Comment by ronsigal** [comment]
Hey @jamezp,

I believe that the main goals here have been achieved. That is, when a gRPC deployment is recognized, a port is opened and all gRPC services in the deployment are registered with the gRPC runtime. Services in all subsequently discovered gRPC deployments are also registered. All of the properties that configure the Netty runtime are exposed. In particular, the presence of a key manager name induces id verification on the client side, and the additional presence of a trust manager name induces id verification on the server side.

What remains is to do the usual subsystem tests. For now, I've been testing manually with the helloworld example, and things seem to work. Also, I'd like to make the examples usable as Arquillian tests.

What do you think of doing an alpha release of what we have?

-Ron

**Review by hpehl — APPROVED** [review]
LGTM. Thanks, @ronsigal and @jamezp

**Pull request merged**
