### PR TITLE
Updated grpc-dependency to remove redundancies

### PR DESCRIPTION
**Pull request by ronsigal**

### CODE REVIEW

**Review by hpehl — COMMENTED** [review]
Is this a replacement for #64

**Comment by ronsigal** [comment]
Hey @hpehl,

Actually, what I've done in this pull request is factor out the redundant jars in the "io.grpc" module (which comes with the WildFly I've been building) and the "org.wildfly.grpc-dependency" module. In particular, I've got "org.wildfly.grpc-dependency" down to grpc-netty-1.38.1.jar and wildfly-grpc-api-0.0.5-SNAPSHOT.jar. Note that "io.grpc" has version 1.38.1, so I used the same version for grpc-netty. I figure that as long as WildFly is shipping with "io.grpc", I would just let the WildFly folks bump that version when they're ready. What do you think?

**Comment by hpehl** [comment]
Sounds reasonable. So I think we can merge this one (after fixing the formatting issues) and close #64)

**Comment by ronsigal** [comment]
I'm not sure what to do. It's saying that 

>2023-02-20T22:17:26.2325505Z ##[error]Changes have been found
2023-02-20T22:17:26.2333321Z  M feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/grpc-dependency/main/module.xml

I guess it means that there's a formatting problem with that file, but I don't see anything wrong with it. I'm using the WildFly format / template files here at home, and I'm not getting any complaints.

**Comment by hpehl** [comment]
Hmm not sure what's wrong here. IMO we can merge this anyway and see if we can fix that later.

**Comment by hpehl** [comment]
@ronsigal I was finally able to find the issue: There was a missing space in `feature-pack/src/main/resources/modules/system/layers/base/org/wildfly/grpc-dependency/main/module.xml`

The strange thing was that the error only occurred in GitHub actions. Anyway, I fixed that, and the builds are green again.

**Comment by ronsigal** [comment]
Hey, @hpehl, I've been meaning to thank you for fixing this.

At this point, do you think there's anything missing from wildfly-grpc-feature-pack?

**Comment by hpehl** [comment]
I haven't followed the development closely lately, but I think you have implemented everything we need for an alpha release.

Unfortunately, I recently got another task. Do you think you can take over the release and community work?

**Comment by ronsigal** [comment]
Ok, sounds good. I've never done that for WildFly, but I'm happy to try. ;-)

**Pull request merged**
