### PR TITLE
Update the feature pack to include both a standard and preview FP plus two other changes

### PR DESCRIPTION
**Pull request by jamezp**
### First Commit - Do not import the component matrix
The component martix is going away in WildFly 28, maybe gone in 27.0.0.Final?, and we should explicitly define the dependencies we need IMO. This allows for easier testing of components and easier upgrades.

### Second Commit - Enable the test suite by default
This is simple as it just enables the test suite by default. Not required, but seemed useful

### Third Commit - Create a standard and preview feature pack
The current feature pack relies on the preview feature pack. However, not that WildFly 27 is Jakarta EE 10, we should have a standard and preview feature pack.

### CODE REVIEW

**Comment by jamezp** [comment]
@jfdenise I feel like I've seen an error like this before and I'm blanking on how to resolve it.
```
Error:  Failed to execute goal org.wildfly.galleon-plugins:wildfly-galleon-maven-plugin:6.3.2.Final:build-feature-pack (wildfly-grpc-feature-pack-build) on project wildfly-grpc-feature-pack: Failed to resolve org.wildfly.galleon-plugins:wildfly-provisioning-parent:pom:6.3.2.Final: Cannot access jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/) in offline mode and the artifact org.wildfly.galleon-plugins:wildfly-provisioning-parent:pom:6.3.2.Final has not been downloaded from it before. -> [Help 1]
```

It's the `org.wildfly.galleon-plugins:wildfly-galleon-maven-plugin:6.3.2.Final:build-feature-pack` working in offline mode, but I don't recall how to change that.

**Comment by jamezp** [comment]
Actually the failure seems to be a regression in 6.3.2 of the `org.wildfly.galleon-plugins:wildfly-galleon-plugins`. My assumption is it might have something to do with https://issues.redhat.com/browse/WFGP-246.

**Comment by jfdenise** [comment]
@jamezp , that is an interesting case. As you said the change is due to [WFGP-246](https://issues.redhat.com/browse/WFGP-246) but I think  something is not fully correct in pom files.

The failing dependency is caused by this dependency (transitive parent from it): https://github.com/jamezp/wildfly-grpc-feature-pack/blob/updates/galleon-pack/feature-pack/pom.xml#L56  and https://github.com/jamezp/wildfly-grpc-feature-pack/blob/updates/galleon-pack/preview-feature-pack/pom.xml#L56
I am not sure you need them.

What happens is that, because this parent is also the wildfly-galleon-maven-plugin parent, it is downloaded first place using the repo for maven plugins configured in the jboss-parent: https://github.com/jboss/jboss-parent-pom/blob/jboss-parent-39/pom.xml#LL1495C5-L1495C5 (jboss-public-repository).
Then, in the set of repositories in use we have: https://github.com/jamezp/wildfly-grpc-feature-pack/blob/updates/pom.xml#L464 (jboss-public-repository-group). The names are different. This makes maven to fail to retrieve in its metadata that the artifact has been downloaded from a configured repository.

So, if you remove the dependency, the problem will go away and you can upgrade to 6.3.2.Final
Or if you really need the dependency (I don't think so)  you can rename the repository to align the repo name with the repo name in jboss-parent so use "jboss-public-repository".

I am also wandering why do we have some duplicated versions in pom.xml and in code-parent/pom.xml.

**Comment by jfdenise** [comment]
@jamezp just curoius, why code-parent/pom.xml and pom.xml have both the plugin version defined?

**Comment by jamezp** [comment]
@jfdenise Good catch. It should probably only be defined in the root `pom.xml`. I'll fix that.

**Comment by jamezp** [comment]
@hpehl Any chance I could get a review on this?

**Comment by hpehl** [comment]
Sorry @jamezp, for the delay. I'll review it later today.

**Pull request merged**
